name: AGCMineral
favicon: null
layout_spectrum: 0.74458
typography_spectrum: 1
title: AGC Mineral Company
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010200'
    - '#fee95c'
    - '#d17c00'
    - '#40a78a'
    - '#1b6a3a'
  brandStrength: 0.9375
  lightness: 0.5
  saturation: 0.9375
  rhythmicContrast: 1
purpose: []
