name: AGCMineral
favicon: null
layout_spectrum: 0.29907260625623167
typography_spectrum: 0.21880841860547662
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.13862048904411495
  lightness: 0.8968895524740219
  saturation: 0.7470473689027131
  rhythmicContrast: 0.9082421269267797
purpose: []
