name: AGCMineral
favicon: null
layout_spectrum: 0.74458
typography_spectrum: 0.48827
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d6c8bb'
    - '#bf9461'
    - '#9b7340'
    - '#452818'
  brandStrength: 0.5
  lightness: 0.8968895524740219
  saturation: 0.7470473689027131
  rhythmicContrast: 0.75
purpose: []
